keys = {
        'url_Jackets': 'https://www.supremenewyork.com/shop/all/jackets',
        'url_Shirts': 'https://www.supremenewyork.com/shop/all/shirts',
        'url_Tops/Sweaters': 'https://www.supremenewyork.com/shop/all/tops_sweaters',
        'url_Sweatshirts': 'https://www.supremenewyork.com/shop/all/sweatshirts',
        'url_Pants': 'https://www.supremenewyork.com/shop/all/pants',
        'url_Shorts': 'https://www.supremenewyork.com/shop/all/shorts',
        'url_T-Shirts': 'https://www.supremenewyork.com/shop/all/t-shirts',
        'url_Hats': 'https://www.supremenewyork.com/shop/all/hats',
        'url_Bags': 'https://www.supremenewyork.com/shop/all/bags',
        'url_acc': 'https://www.supremenewyork.com/shop/all/accessories',
        'url_Skate': 'https://www.supremenewyork.com/shop/all/skate',
        '#_of_products': '1',
        'product1': ['Name Badge Stickers (Pack of 100)', 'Red', 'acc'],
        'product2': ['Static Sweater', 'Black', 'Tops/Sweaters'],
        'product3': ['Portrait Hooded Sweatshirt', 'Dark Olive', 'Sweatshirts'],
        'name': 'Bryan Saldana',
        'email': '214188625@madisonhs.org',
        'phone': '347 666 7919',
        'address': '7807 20th Avenue',
        'zip': '11214',
        'card': '5211 0500 0400 4353',
        'cvv': '50'
}
