keys = {
        'url_jacket': 'https://www.supremenewyork.com/shop/all/jackets',
        'url_shirt': 'https://www.supremenewyork.com/shop/all/shirts',
        'url_sweater': 'https://www.supremenewyork.com/shop/all/tops_sweaters',
        'url_sweatshirt': 'https://www.supremenewyork.com/shop/all/sweatshirts',
        'url_pants': 'https://www.supremenewyork.com/shop/all/pants',
        'url_shorts': 'https://www.supremenewyork.com/shop/all/shorts',
        'url_t-shirts': 'https://www.supremenewyork.com/shop/all/t-shirts',
        'url_hat': 'https://www.supremenewyork.com/shop/all/hats',
        'url_bag': 'https://www.supremenewyork.com/shop/all/bags',
        'url_acc': 'https://www.supremenewyork.com/shop/all/accessories',
        'url_skate': 'https://www.supremenewyork.com/shop/all/skate',
        '#_of_products': '1',
        'product1': ['Camo', 'shirt'],
        'product2': ['Oxford', 'shirt'],
        'product3': ['Leopard', 'bag'],
        'name': 'John Smith',
        'email': 'Smith@aol.com',
        'phone': '123-456-7980',
        'address': '1233 aoeu Avenue',
        'zip': '11216',
        'card': '4111 1111 1111 1111',
        'cvv': '503'
}
